version: '3.8'

services:
  backend:
    build: 
      context: ./server
    container_name: express-backend
    ports:
      - "5000:5900"  # Map localhost:5000 â†’ container:5900
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://jagwarauth:FuckYouSabnur@jagwarcluster.jsrzyzq.mongodb.net/test?retryWrites=true&w=majority&appName=jagwarcluster
    volumes:
      - ./server:/app
      - /app/node_modules